# Generated by Django 2.1.7 on 2019-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Аватар'),
        ),
    ]
